### ISSUE TITLE
请问可以将用户名密码放置在一个文件中，在终端登陆时直接调用吗？

### ISSUE THREAD

**Issue by jcx70100** [ShanghaitechGeekPie/WifiLoginer#12]
请问可以将用户名密码放置在一个文件中，在终端登陆时直接调用吗？
比如用户名密码保存在login文件中，在终端执行登陆时直接输入./*** login，这样是否可行，
具体要怎么操作，代码部分要做修改吗？

**Comment by nerdroychan** [comment]
可以看一下各种语言的文件 IO 操作。
