### ISSUE TITLE
关于学校 SSL 证书与登陆验证连接

### ISSUE THREAD

**Issue by lirundong** [ShanghaitechGeekPie/WifiLoginer#7]
在使用 `Python3` 或 `wget` 进行登陆时，会出现以下错误：
```python3
CertificateError: hostname 'controller1.net.shanghaitech.edu.cn' doesn't match either of '*.shanghaitech.edu.cn', 'shanghaitech.edu.cn'
```
似乎是由于学校的 SSL 证书只能覆盖到域名的下一级，而 `controller1.net.`  无法被 SSL 覆盖。浏览了下登录页面的 JS 脚本，POST 的地址为
```JavaScript
$.post("../../../Webauth/webAuthAction!login.action", params, function (json) {
        onProcess = !1, loginResponse(json)
    })
```
不太熟悉网络编程，不知 dalao 们能不能解决下这个问题。谢谢~

**Comment by wtlyu** [comment]
@nerdroychan

**Comment by wtlyu** [comment]
@zeanzhou

**Comment by EricDiao** [comment]
ezwifiloginer 的错误信息：
`Logining…… Unknown Error! Is the network available?
EOF occurred in violation of protocol (_ssl.c:590)`

**Comment by zeanzhou** [comment]
#8 认证界面的发生过变更，修改成新地址即可

**Comment by wtlyu** [comment]
merged。 @EricDiao @CrazyRundong 请pull一下试试？

**Comment by nerdneilsfield** [comment]
稍等一下，我改一下。

**Comment by nerdneilsfield** [comment]
Shell 的两个版本都已经修复，我把证书验证都关了。

**Comment by nerdneilsfield** [comment]
Powershell 的也顺便改了。

**Comment by lirundong** [comment]
Hi  @eastpiger   @nerdneilsfield , `Python3` 的 `login` 函数调用仍然会发生 `CertificateError` 错误；`wget` 版不会报错，但是在寝室的 synology DSM 系统上试了下，并不能完成验证

**Comment by zeanzhou** [comment]
@CrazyRundong Sorry I didn't run a full test before the last commit. Try again now, plz.
BTW, you AT wrong persons...

**Comment by lirundong** [comment]
Hi @zeanzhou , the `Python3` version works pretty fine now, thx~

**Comment by zeanzhou** [comment]
@CrazyRundong You're welcome, thanks for your report =)

**Comment by zeanzhou** [comment]
@CrazyRundong You're welcome, thanks for your report =)
